version: '3'

services:
#  redis:
#    image: "redis:6.2.3"
#    hostname: redis
#    networks:
#      - epith
#    healthcheck:
#      test: ["CMD", "redis-cli", "ping"]
#      interval: 30s
#      timeout: 30s
#      retries: 3
#    logging:
#      options:
#        max-size: 200m
#    restart: unless-stopped

  server:
    build: .
    networks:
      - epith
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./storage:/back/storage
#      - ./api:/back/api
#      - ./app.py:/back/app.py
#      - ./static:/back/static
#      - ./templates:/back/templates
#      - ./utils:/back/utils
#      - ./configs:/back/configs

#
#  tdm-rq-monitor:
#    image: "pranavgupta1234/rqmonitor"
##    tty: true
#    environment:
#      - RQ_MONITOR_REDIS_URL=redis://redis:6379/1
#    ports:
#      - 8899:8899
#    networks:
#      - epith
#    restart: always
#    depends_on:
#      - redis



networks:
  epith:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24